
package br.furb.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GitCloneWeb", targetNamespace = "http://webservice.furb.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GitCloneWeb {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cloneRepository", targetNamespace = "http://webservice.furb.br/", className = "br.furb.webservice.client.CloneRepository")
    @ResponseWrapper(localName = "cloneRepositoryResponse", targetNamespace = "http://webservice.furb.br/", className = "br.furb.webservice.client.CloneRepositoryResponse")
    @Action(input = "http://webservice.furb.br/GitCloneWeb/cloneRepositoryRequest", output = "http://webservice.furb.br/GitCloneWeb/cloneRepositoryResponse")
    public boolean cloneRepository(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
