
package br.furb.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginWeb", targetNamespace = "http://webservice.furb.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginWeb {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.furb.br/", className = "br.furb.webservice.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.furb.br/", className = "br.furb.webservice.client.LoginResponse")
    @Action(input = "http://webservice.furb.br/LoginWeb/loginRequest", output = "http://webservice.furb.br/LoginWeb/loginResponse")
    public boolean login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
