package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/History_Status.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 17h28min38s BRST
*/

public class History_Status implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static br.furb.corba.configuration.stubs.History_Status[] __array = new br.furb.corba.configuration.stubs.History_Status [__size];

  public static final int _SUCCESS = 0;
  public static final br.furb.corba.configuration.stubs.History_Status SUCCESS = new br.furb.corba.configuration.stubs.History_Status(_SUCCESS);
  public static final int _FAIL = 1;
  public static final br.furb.corba.configuration.stubs.History_Status FAIL = new br.furb.corba.configuration.stubs.History_Status(_FAIL);

  public int value ()
  {
    return __value;
  }

  public static br.furb.corba.configuration.stubs.History_Status from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected History_Status (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class History_Status
