package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/History_StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 17h28min38s BRST
*/

abstract public class History_StatusHelper
{
  private static String  _id = "IDL:br/furb/corba/configuration/stubs/History_Status:1.0";

  public static void insert (org.omg.CORBA.Any a, br.furb.corba.configuration.stubs.History_Status that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.furb.corba.configuration.stubs.History_Status extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (br.furb.corba.configuration.stubs.History_StatusHelper.id (), "History_Status", new String[] { "SUCCESS", "FAIL"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.furb.corba.configuration.stubs.History_Status read (org.omg.CORBA.portable.InputStream istream)
  {
    return br.furb.corba.configuration.stubs.History_Status.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.furb.corba.configuration.stubs.History_Status value)
  {
    ostream.write_long (value.value ());
  }

}
