package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/Job.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Domingo, 30 de Novembro de 2014 20h33min58s BRST
*/

public final class Job implements org.omg.CORBA.portable.IDLEntity
{
  public String job_nome = null;
  public br.furb.corba.configuration.stubs.JobType job_type = null;
  public String repository_Path = null;

  public Job ()
  {
  } // ctor

  public Job (String _job_nome, br.furb.corba.configuration.stubs.JobType _job_type, String _repository_Path)
  {
    job_nome = _job_nome;
    job_type = _job_type;
    repository_Path = _repository_Path;
  } // ctor

} // class Job
