package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/Job_History.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 17h28min38s BRST
*/

public final class Job_History implements org.omg.CORBA.portable.IDLEntity
{
  public long dateInMillis = (long)0;
  public String log = null;
  public br.furb.corba.configuration.stubs.History_Status status = null;

  public Job_History ()
  {
  } // ctor

  public Job_History (long _dateInMillis, String _log, br.furb.corba.configuration.stubs.History_Status _status)
  {
    dateInMillis = _dateInMillis;
    log = _log;
    status = _status;
  } // ctor

} // class Job_History
