package br.furb.corba.configuration.stubs;

/**
* br/furb/corba/configuration/stubs/Job_HistoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 19h30min17s BRST
*/

public final class Job_HistoryHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.corba.configuration.stubs.Job_History value = null;

  public Job_HistoryHolder ()
  {
  }

  public Job_HistoryHolder (br.furb.corba.configuration.stubs.Job_History initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.corba.configuration.stubs.Job_HistoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.corba.configuration.stubs.Job_HistoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.corba.configuration.stubs.Job_HistoryHelper.type ();
  }

}
