package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/job_managerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Domingo, 30 de Novembro de 2014 20h33min58s BRST
*/

public interface job_managerOperations 
{
  void save (br.furb.corba.configuration.stubs.Job job);
  boolean exist (String job_nome, org.omg.CORBA.BooleanHolder ret);
  void delete (String job_nome);
  boolean load (String path, br.furb.corba.configuration.stubs.JobHolder ret);
  boolean load_all (br.furb.corba.configuration.stubs.arrayJobsHolder jobs);
} // interface job_managerOperations
