package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/job_managerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 19h30min17s BRST
*/

public interface job_managerOperations 
{
  void save (br.furb.corba.configuration.stubs.Job_ job);
  boolean exist (String job_nome, org.omg.CORBA.BooleanHolder ret);
  void delete (String job_nome);
  boolean load (String path, br.furb.corba.configuration.stubs.Job_Holder ret);
  boolean load_all (br.furb.corba.configuration.stubs.arrayJobsHolder jobs);
  void add_history (String job_nome, br.furb.corba.configuration.stubs.Job_History history);
  boolean loadHistorys (String job_nome, br.furb.corba.configuration.stubs.arrayJobsHistoryHolder historys);
} // interface job_managerOperations
