package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/job_manager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 17h28min38s BRST
*/

public interface job_manager extends job_managerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface job_manager
