package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/Job_HistoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 19h30min17s BRST
*/

abstract public class Job_HistoryHelper
{
  private static String  _id = "IDL:br/furb/corba/configuration/stubs/Job_History:1.0";

  public static void insert (org.omg.CORBA.Any a, br.furb.corba.configuration.stubs.Job_History that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.furb.corba.configuration.stubs.Job_History extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "dateInMillis",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "log",
            _tcOf_members0,
            null);
          _tcOf_members0 = br.furb.corba.configuration.stubs.History_StatusHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "status",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (br.furb.corba.configuration.stubs.Job_HistoryHelper.id (), "Job_History", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.furb.corba.configuration.stubs.Job_History read (org.omg.CORBA.portable.InputStream istream)
  {
    br.furb.corba.configuration.stubs.Job_History value = new br.furb.corba.configuration.stubs.Job_History ();
    value.dateInMillis = istream.read_longlong ();
    value.log = istream.read_string ();
    value.status = br.furb.corba.configuration.stubs.History_StatusHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.furb.corba.configuration.stubs.Job_History value)
  {
    ostream.write_longlong (value.dateInMillis);
    ostream.write_string (value.log);
    br.furb.corba.configuration.stubs.History_StatusHelper.write (ostream, value.status);
  }

}
