package br.furb.corba.configuration.stubs;

/**
* br/furb/corba/configuration/stubs/job_managerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 17h28min38s BRST
*/

public final class job_managerHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.corba.configuration.stubs.job_manager value = null;

  public job_managerHolder ()
  {
  }

  public job_managerHolder (br.furb.corba.configuration.stubs.job_manager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.corba.configuration.stubs.job_managerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.corba.configuration.stubs.job_managerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.corba.configuration.stubs.job_managerHelper.type ();
  }

}
