package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/Job_Type.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Terça-feira, 2 de Dezembro de 2014 19h30min17s BRST
*/

public class Job_Type implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static br.furb.corba.configuration.stubs.Job_Type[] __array = new br.furb.corba.configuration.stubs.Job_Type [__size];

  public static final int _CLONE = 0;
  public static final br.furb.corba.configuration.stubs.Job_Type CLONE = new br.furb.corba.configuration.stubs.Job_Type(_CLONE);
  public static final int _COMPILATION = 1;
  public static final br.furb.corba.configuration.stubs.Job_Type COMPILATION = new br.furb.corba.configuration.stubs.Job_Type(_COMPILATION);
  public static final int _BUILD = 2;
  public static final br.furb.corba.configuration.stubs.Job_Type BUILD = new br.furb.corba.configuration.stubs.Job_Type(_BUILD);
  public static final int _TEST = 3;
  public static final br.furb.corba.configuration.stubs.Job_Type TEST = new br.furb.corba.configuration.stubs.Job_Type(_TEST);

  public int value ()
  {
    return __value;
  }

  public static br.furb.corba.configuration.stubs.Job_Type from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Job_Type (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Job_Type
