package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/job_manager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Domingo, 30 de Novembro de 2014 20h33min58s BRST
*/

public interface job_manager extends job_managerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface job_manager
