package br.furb.corba.configuration.stubs;

/**
* br/furb/corba/configuration/stubs/JobHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Domingo, 30 de Novembro de 2014 20h33min58s BRST
*/

public final class JobHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.corba.configuration.stubs.Job value = null;

  public JobHolder ()
  {
  }

  public JobHolder (br.furb.corba.configuration.stubs.Job initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.corba.configuration.stubs.JobHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.corba.configuration.stubs.JobHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.corba.configuration.stubs.JobHelper.type ();
  }

}
