package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/JobHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Domingo, 30 de Novembro de 2014 20h33min58s BRST
*/

abstract public class JobHelper
{
  private static String  _id = "IDL:br/furb/corba/configuration/stubs/Job:1.0";

  public static void insert (org.omg.CORBA.Any a, br.furb.corba.configuration.stubs.Job that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.furb.corba.configuration.stubs.Job extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "job_nome",
            _tcOf_members0,
            null);
          _tcOf_members0 = br.furb.corba.configuration.stubs.JobTypeHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "job_type",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "repository_Path",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (br.furb.corba.configuration.stubs.JobHelper.id (), "Job", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.furb.corba.configuration.stubs.Job read (org.omg.CORBA.portable.InputStream istream)
  {
    br.furb.corba.configuration.stubs.Job value = new br.furb.corba.configuration.stubs.Job ();
    value.job_nome = istream.read_string ();
    value.job_type = br.furb.corba.configuration.stubs.JobTypeHelper.read (istream);
    value.repository_Path = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.furb.corba.configuration.stubs.Job value)
  {
    ostream.write_string (value.job_nome);
    br.furb.corba.configuration.stubs.JobTypeHelper.write (ostream, value.job_type);
    ostream.write_string (value.repository_Path);
  }

}
