package br.furb.corba.configuration.stubs;


/**
* br/furb/corba/configuration/stubs/JobType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from JobManager.idl
* Domingo, 30 de Novembro de 2014 20h33min58s BRST
*/

public class JobType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static br.furb.corba.configuration.stubs.JobType[] __array = new br.furb.corba.configuration.stubs.JobType [__size];

  public static final int _COMPILATION = 0;
  public static final br.furb.corba.configuration.stubs.JobType COMPILATION = new br.furb.corba.configuration.stubs.JobType(_COMPILATION);
  public static final int _BUILD = 1;
  public static final br.furb.corba.configuration.stubs.JobType BUILD = new br.furb.corba.configuration.stubs.JobType(_BUILD);

  public int value ()
  {
    return __value;
  }

  public static br.furb.corba.configuration.stubs.JobType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected JobType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class JobType
