// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package br.furb.rmi;

public final class BuilderServer_Stub
    extends java.rmi.server.RemoteStub
    implements br.furb.rmi.Builder, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_compile_0;
    private static java.lang.reflect.Method $method_packageJar_1;
    private static java.lang.reflect.Method $method_test_2;
    
    static {
	try {
	    $method_compile_0 = br.furb.rmi.Builder.class.getMethod("compile", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_packageJar_1 = br.furb.rmi.Builder.class.getMethod("packageJar", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_test_2 = br.furb.rmi.Builder.class.getMethod("test", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public BuilderServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of compile(String, String)
    public boolean compile(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_compile_0, new java.lang.Object[] {$param_String_1, $param_String_2}, 2782277037132248861L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of packageJar(String, String)
    public boolean packageJar(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_packageJar_1, new java.lang.Object[] {$param_String_1, $param_String_2}, 198874820607884380L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of test(String, String)
    public boolean test(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_test_2, new java.lang.Object[] {$param_String_1, $param_String_2}, -4661544596283769655L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
